#Esse é um comentário no Python.
# A função dos comentários é explicar o código e organiza-lo 

# O Python é uma linguagem de programação dinâmica e interpretada.
# Compilação: significa que a linguagem é processada antes por um programa "Compilador" e transformada em um arquivo binário executável.
# Interpretação: significa que a linguagem é processada, a sua instrução, por instrução de um programa interpretador.
# Um código Python é um conjunto de símbolos e regras pré-definidas dessa linguagem.

# Um código em Python ele deve possuir a extensão .py

# Notebook (.ipynb) tem como objetivo a apresentação de resultados, ele permite tanto Python quanto linguagem de marcação de texto como HTML.